apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: store-app-gateway
  namespace: store-app
  annotations:
    alb.networking.azure.io/alb-id: /subscriptions/147f910d-d9c8-40ca-8455-2ea5219765e5/resourceGroups/rg-sreagt-dmo-swc-001/providers/Microsoft.ServiceNetworking/trafficControllers/tc-sreagt-store-dmo-swc-001
    alb.networking.azure.io/alb-frontend: fe-public-001
spec:
  gatewayClassName: azure-alb-external
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
